<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('destinations', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('address');
            $table->decimal('price', 12,2)->default(0);
            $table->string('estimation-time');
            $table->string('status')->default('active');
            $table->timestamps();
            $table->softDeletes();
        });

        // pending, accepted, cancelled, completed
        Schema::create('order_statuses', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('description');
            $table->timestamps();
        });

        Schema::create('reasons', function (Blueprint $table) {
            $table->id();
            $table->string('label');
            $table->string('value');
            $table->timestamps();
        });

        Schema::create('orders', function (Blueprint $table) {
            $table->id();
            $table->string('reference_code')->unique(); // unique code generated by system
            $table->foreignId('wallet_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('order_status_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('customer_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('destination_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('driver_id')->nullable()->constrained()->nullOnDelete();
            $table->dateTime('pickup_time');
            $table->dateTime('dropoff_time');
            $table->boolean('cancellable')->default(true); // false > 3 minutes after order is placed
            $table->string('reason')->nullable(); // reason for cancellation
            $table->decimal('total_price', 12,2)->default(0);
            $table->boolean('')->default(false);
            $table->timestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('orders');
    }
};
